### ISSUE TITLE
fail to deploy after upgrade to Kotlin 1.4.0

### ISSUE THREAD

**Issue by oshai** [MicroUtils/kotlin-logging#130]
Issue #127 upgraded the lib to Kotlin 1.4.0.
It seems that after the push deployment is not working anymore.
I created an issue and there are more details on [youtrack](https://youtrack.jetbrains.com/issue/KT-41483).

What's important for the lib now is that all `1.9.x` and `1.10.x` versions are malformed and shouldn't be use.
The known good version is `1.8.3`, so please use this one until solved or reverted.

**Comment by altavir** [comment]
The bintray plugin is known to be bugged. It is missing gradle metadata module. The module must be added manually. I've stopped using it and now I am using regular maven-publish plugin: https://github.com/mipt-npm/scientifik-gradle-tools/blob/master/src/main/kotlin/ru/mipt/npm/gradle/KSciencePublishPlugin.kt. It requires manually creating packages on the bintray for new artifacts, but otherwise, it is much more reliable.

Also since 1.4, the package naming patter is changed, `-common` should not be there anymore. You should use no suffixes for common module `-jvm` for jvm and `-js` for js. But those are managed automatically by kotlin plugin.

**Comment by altavir** [comment]
Since I need the library ASAP to continue development, I've made a fork and published artifacts to the GitHub packages: https://github.com/altavir/kotlin-logging/packages.  The workaround for bintray plugin bug could be found here: https://github.com/mipt-npm/scientifik-gradle-tools/blob/6464d9d926043b4e8ed5af0c4ef27c64f0934f59/build.gradle.kts#L135

**Comment by oshai** [comment]
I'll do the package rename only if it will be very complicated to keep the old schema, because this is a breaking change.
Thanks for the workaround, I will try it out.

**Comment by altavir** [comment]
It is not a package name, it is an artifact name. It does not affect anything but Gradle dependency suffix.And those are dropped anyway. Since 1.4 suffixless dependencies are used both for mpp common and platform versions.

**Comment by oshai** [comment]
Changing the artifact name is a breaking change and can create a mess. Imagine that you moved to the new name but a lib you depend on use the old name or vice versa. Gradle is not aware it's the same package which can cause collision of classes and issues on every tiny change due to wrong class being loaded.

**Comment by oshai** [comment]
found the doc that might help: https://kotlinlang.org/docs/reference/migrating-multiplatform-project-to-14.html#for-library-authors

**Comment by oshai** [comment]
This issue is fixed, although there has been some other issue #144 .
