### ISSUE TITLE
When an error occurs in Log message invocation then log it as an ERROR

### ISSUE THREAD

**Issue by kemalizing** [MicroUtils/kotlin-logging#160]
Hi,

We are using kotlin-logging on many services on production. Today we figured out that if a message lambda fails, that incident is logged with the initial logging level, while it is actually an error. Which leads to some unexpected behavior. 

Basically I'm speaking about this log `"Log message invocation failed: $e"` coming from `toStringSafe` method.

Is it possible to log that exception in ERROR level? 

Thanks.
Kind regards

**Comment by oshai** [comment]
For reference, this is the original issue it was added: https://github.com/MicroUtils/kotlin-logging/pull/22

It's not so obvious how to implement that, and what the logging level should be (error? warn?) because this methos is just returning a string. 
What I suggest is adding a jvm param to throw the exception, then users can do whatever they decide to do with it.
What do you think?

**Comment by kemalizing** [comment]
Thanks for the quick response. 

I like your idea of throwing an exception. If I've a problem in my code, the lambda in this case, I'd like to see it as an exception in my service, totally makes sense.

**Comment by oshai** [comment]
@kemalizing - please let me know if the PR looks as you expect.

**Comment by kemalizing** [comment]
Looks good, thanks for the quick fix!

**Comment by oshai** [comment]
fixed in 2.0.4 and added some docs in the wiki: https://github.com/MicroUtils/kotlin-logging/wiki#q-what-happen-if-an-exception-is-thrown-when-creating-a-log-message
