### ISSUE TITLE
Have to use companion object for something else too

### ISSUE THREAD

**Issue by atistrcsn** [MicroUtils/kotlin-logging#26]
@oshai First of all: AWESOME LIB! 🏆 

But...I really want something like this...
``` kotlin
companion object {
        const val VIEW_NAME = ""
        val logger = KLogging().logger()
    }
    
    fun some() { logger.debug {"foo bar"}}
```
Unfortunately this way your library uses it's own class (mu.Klogging) in the log file:

```
2017-09-22 11:10:24.831  INFO 5919 --- [nio-8082-exec-6] mu.KLogging                              : foo bar
```
Is there a kotlin way that I can use the companion object for something else too?

**Comment by oshai** [comment]
Thanks! Can you explain the use case exactly? Why the current 2 flavours
are not enough?

**Comment by atistrcsn** [comment]
Is there a second flavour? 😃

**Comment by oshai** [comment]
Put it as a field in file outside of the class, actually this is my
favourite:

   - Define the logger, without explicitly specifiying the class name:

private val logger = KotlinLogging.logger {}


On 22 Sep 2017 18:07, "Attila Turcsan" <notifications@github.com> wrote:

Is there a second flavour? 😃

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MicroUtils/kotlin-logging/issues/26#issuecomment-331473805>,
or mute the thread

**Comment by atistrcsn** [comment]
> outside of the class
Thanks. This was not clear to me. I put it INSIDE of the class 😃

**Comment by oshai** [comment]
Great, I will improve the readme, or your welcome to do that as a pull
request.
