### ISSUE TITLE
Need a guide setting up JS flavor

### ISSUE THREAD

**Issue by aviadmini** [MicroUtils/kotlin-logging#58]
Adding `compile 'io.github.microutils:kotlin-logging:1.6.20'` to Gradle dependencies only pulls jvm and common artifacts, and can't be used for a js project

**Comment by oshai** [comment]
The correct dependency for js platform is compile 'io.github.microutils:kotlin-logging-js:1.6.22'

Changes are the artifact for js is kotlin-logging-js and version should be 1.6.22 because of a bug fix in that version.

More info here: https://github.com/MicroUtils/kotlin-logging/wiki/Multiplatform-support

Let me know if that helps.

**Comment by oshai** [comment]
@aviadmini - can I close this issue?
